// _react-reference/src/components/ImageGallerySlider.tsx
import { useCallback, useEffect, useRef, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronLeft, ChevronRight } from 'lucide-react';

interface GalleryImage {
  src: string;
  alt: string;
}

interface ImageGallerySliderProps {
  images: GalleryImage[];
  autoPlayInterval?: number;
}

const ImageGallerySlider = ({ images, autoPlayInterval = 4000 }: ImageGallerySliderProps) => {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [direction, setDirection] = useState(1);
  const [isHovered, setIsHovered] = useState(false);
  const intervalRef = useRef<NodeJS.Timeout | null>(null);

  const startAutoPlay = useCallback(() => {
    if (intervalRef.current) clearInterval(intervalRef.current);
    intervalRef.current = setInterval(() => {
      setDirection(1);
      setCurrentIndex((prev) => (prev + 1) % images.length);
    }, autoPlayInterval);
  }, [images.length, autoPlayInterval]);

  const stopAutoPlay = () => {
    if (intervalRef.current) {
      clearInterval(intervalRef.current);
      intervalRef.current = null;
    }
  };

  useEffect(() => {
    if (!isHovered) {
      startAutoPlay();
    }
    return () => stopAutoPlay();
  }, [isHovered, startAutoPlay]);

  const goToNext = () => {
    setDirection(1);
    setCurrentIndex((prev) => (prev + 1) % images.length);
    startAutoPlay();
  };

  const goToPrev = () => {
    setDirection(-1);
    setCurrentIndex((prev) => (prev - 1 + images.length) % images.length);
    startAutoPlay();
  };

  const goToSlide = (index: number) => {
    setDirection(index > currentIndex ? 1 : -1);
    setCurrentIndex(index);
    startAutoPlay();
  };

  const slideVariants = {
    enter: (direction: number) => ({
      x: direction > 0 ? 300 : -300,
      opacity: 0,
      scale: 0.95,
    }),
    center: {
      x: 0,
      opacity: 1,
      scale: 1,
    },
    exit: (direction: number) => ({
      x: direction > 0 ? -300 : 300,
      opacity: 0,
      scale: 0.95,
    }),
  };

  return (
    <div
      className="group relative w-full overflow-hidden rounded-xl bg-gradient-to-br from-accent/5 to-primary/5 p-1"
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
    >
      {/* Main Image Container */}
      <div className="relative aspect-[4/3] w-full overflow-hidden rounded-lg bg-card">
        <AnimatePresence mode="wait" custom={direction}>
          <motion.div
            key={currentIndex}
            custom={direction}
            variants={slideVariants}
            initial="enter"
            animate="center"
            exit="exit"
            transition={{
              x: { type: 'spring', stiffness: 300, damping: 30 },
              opacity: { duration: 0.3 },
              scale: { duration: 0.3 },
            }}
            className="absolute inset-0"
          >
            <img
              src={images[currentIndex].src}
              alt={images[currentIndex].alt}
              decoding="async"
              className="h-full w-full object-cover"
            />
            {/* Gradient Overlay */}
            <div className="absolute inset-0 bg-gradient-to-t from-background/60 via-transparent to-transparent" />
          </motion.div>
        </AnimatePresence>

        {/* Navigation Arrows */}
        <button
          onClick={goToPrev}
          className="absolute left-3 top-1/2 -translate-y-1/2 p-2 rounded-full bg-background/80 backdrop-blur-sm border border-border hover:bg-accent/20 hover:border-accent transition-all duration-300 opacity-70 sm:opacity-0 sm:group-hover:opacity-100 z-10"
          aria-label="Previous image"
        >
          <ChevronLeft className="w-5 h-5 text-foreground" />
        </button>
        <button
          onClick={goToNext}
          className="absolute right-3 top-1/2 -translate-y-1/2 p-2 rounded-full bg-background/80 backdrop-blur-sm border border-border hover:bg-accent/20 hover:border-accent transition-all duration-300 opacity-70 sm:opacity-0 sm:group-hover:opacity-100 z-10"
          aria-label="Next image"
        >
          <ChevronRight className="w-5 h-5 text-foreground" />
        </button>

        {/* Image Counter */}
        <div className="absolute top-3 right-3 px-3 py-1 rounded-full bg-background/80 backdrop-blur-sm border border-border text-xs text-foreground font-medium">
          {currentIndex + 1} / {images.length}
        </div>
      </div>

      {/* Dot Indicators */}
      <div className="flex justify-center gap-2 mt-4 pb-2">
        {images.map((_, index) => (
          <button
            key={index}
            onClick={() => goToSlide(index)}
            className={`transition-all duration-300 rounded-full ${
              index === currentIndex
                ? 'w-6 h-2 bg-accent'
                : 'w-2 h-2 bg-muted-foreground/40 hover:bg-muted-foreground/60'
            }`}
            aria-label={`Go to slide ${index + 1}`}
          />
        ))}
      </div>

      {/* Thumbnail Strip */}
      <div className="flex gap-2 mt-2 overflow-x-auto pb-2 px-1 scrollbar-hide">
        {images.map((image, index) => (
          <motion.button
            key={index}
            onClick={() => goToSlide(index)}
            className={`relative flex-shrink-0 w-16 h-12 rounded-md overflow-hidden border-2 transition-all duration-300 ${
              index === currentIndex
                ? 'border-accent ring-2 ring-accent/30'
                : 'border-transparent hover:border-accent/50'
            }`}
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
          >
            <img
              src={image.src}
              alt={image.alt}
              loading="lazy"
              decoding="async"
              width={64}
              height={48}
              className="w-full h-full object-cover"
            />
            {index === currentIndex && (
              <div className="absolute inset-0 bg-accent/20" />
            )}
          </motion.button>
        ))}
      </div>
    </div>
  );
};

export default ImageGallerySlider;

// resources/js/Components/Portfolio/ImageGallerySlider.vue
<script setup>
import { ref, onMounted, onUnmounted } from 'vue';
import { ChevronLeft, ChevronRight } from '@lucide/vue';

const props = defineProps({
    images: { type: Array, required: true }, // [{ src, alt }]
    autoPlayInterval: { type: Number, default: 4000 },
});

const currentIndex = ref(0);
const isHovered = ref(false);
let intervalId = null;

function startAutoPlay() {
    stopAutoPlay();
    intervalId = setInterval(() => {
        currentIndex.value = (currentIndex.value + 1) % props.images.length;
    }, props.autoPlayInterval);
}

function stopAutoPlay() {
    if (intervalId) {
        clearInterval(intervalId);
        intervalId = null;
    }
}

function goToNext() {
    currentIndex.value = (currentIndex.value + 1) % props.images.length;
    startAutoPlay();
}

function goToPrev() {
    currentIndex.value = (currentIndex.value - 1 + props.images.length) % props.images.length;
    startAutoPlay();
}

function goToSlide(index) {
    currentIndex.value = index;
    startAutoPlay();
}

onMounted(() => {
    if (!isHovered.value) startAutoPlay();
});

onUnmounted(() => {
    stopAutoPlay();
});
</script>

<template>
    <div
        class="group relative w-full overflow-hidden rounded-xl bg-gradient-to-br from-accent/5 to-primary/5 p-1"
        @mouseenter="isHovered = true; stopAutoPlay()"
        @mouseleave="isHovered = false; startAutoPlay()"
    >
        <!-- Main Image Container -->
        <div class="relative aspect-[4/3] w-full overflow-hidden rounded-lg bg-card">
            <Transition name="slide-fade" mode="out-in">
                <div :key="currentIndex" class="absolute inset-0">
                    <img
                        :src="images[currentIndex].src"
                        :alt="images[currentIndex].alt"
                        decoding="async"
                        class="h-full w-full object-cover"
                    />
                    <div class="absolute inset-0 bg-gradient-to-t from-background/60 via-transparent to-transparent" />
                </div>
            </Transition>

            <button
                v-if="images.length > 1"
                @click="goToPrev"
                class="absolute left-3 top-1/2 -translate-y-1/2 p-2 rounded-full bg-background/80 backdrop-blur-sm border border-border hover:bg-accent/20 hover:border-accent transition-all duration-300 opacity-70 sm:opacity-0 sm:group-hover:opacity-100 z-10"
                aria-label="Previous image"
            >
                <ChevronLeft class="w-5 h-5 text-foreground" />
            </button>
            <button
                v-if="images.length > 1"
                @click="goToNext"
                class="absolute right-3 top-1/2 -translate-y-1/2 p-2 rounded-full bg-background/80 backdrop-blur-sm border border-border hover:bg-accent/20 hover:border-accent transition-all duration-300 opacity-70 sm:opacity-0 sm:group-hover:opacity-100 z-10"
                aria-label="Next image"
            >
                <ChevronRight class="w-5 h-5 text-foreground" />
            </button>

            <div class="absolute top-3 right-3 px-3 py-1 rounded-full bg-background/80 backdrop-blur-sm border border-border text-xs text-foreground font-medium">
                {{ currentIndex + 1 }} / {{ images.length }}
            </div>
        </div>

        <!-- Dot Indicators -->
        <div class="flex justify-center gap-2 mt-4 pb-2">
            <button
                v-for="(_, index) in images"
                :key="index"
                @click="goToSlide(index)"
                class="transition-all duration-300 rounded-full"
                :class="index === currentIndex ? 'w-6 h-2 bg-accent' : 'w-2 h-2 bg-muted-foreground/40 hover:bg-muted-foreground/60'"
                :aria-label="`Go to slide ${index + 1}`"
            />
        </div>

        <!-- Thumbnail Strip -->
        <div class="flex gap-2 mt-2 overflow-x-auto pb-2 px-1 scrollbar-hide">
            <button
                v-for="(image, index) in images"
                :key="index"
                @click="goToSlide(index)"
                class="relative flex-shrink-0 w-16 h-12 rounded-md overflow-hidden border-2 transition-all duration-300 hover:scale-105"
                :class="index === currentIndex ? 'border-accent ring-2 ring-accent/30' : 'border-transparent hover:border-accent/50'"
            >
                <img
                    :src="image.src"
                    :alt="image.alt"
                    loading="lazy"
                    decoding="async"
                    width="64"
                    height="48"
                    class="w-full h-full object-cover"
                />
                <div v-if="index === currentIndex" class="absolute inset-0 bg-accent/20" />
            </button>
        </div>
    </div>
</template>

<style scoped>
.slide-fade-enter-active,
.slide-fade-leave-active {
    transition: all 0.3s ease;
}
.slide-fade-enter-from {
    opacity: 0;
    transform: scale(0.95) translateX(30px);
}
.slide-fade-leave-to {
    opacity: 0;
    transform: scale(0.95) translateX(-30px);
}
</style>
